=== UbuntuBudgie/Website/.astro/collections/downloads-settings.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "donationTitle": {
      "type": "string"
    },
    "donationDescription": {
      "type": "string"
    },
    "tip1Label": {
      "type": "string"
    },
    "tip1Url": {
      "type": "string"
    },
    "tip2Label": {
      "type": "string"
    },
    "tip2Url": {
      "type": "string"
    },
    "tip3Label": {
      "type": "string"
    },
    "tip3Url": {
      "type": "string"
    },
    "tip4Label": {
      "type": "string"
    },
    "tip4Url": {
      "type": "string"
    },
    "usbDescription": {
      "type": "string"
    },
    "usbButtonText": {
      "type": "string"
    },
    "usbButtonUrl": {
      "type": "string"
    },
    "installationTitle": {
      "type": "string"
    },
    "installationContent": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  }
}

=== UbuntuBudgie/Website/src/content/downloads-settings/downloads-settings.json
{
  "donationTitle": "A little bit goes a long way.",
  "donationDescription": "If everyone who downloaded Ubuntu Budgie donated £5 it would fund the continued development of Ubuntu Budgie. Please help the project flourish by showing your support with a tip.",
  "tip1Label": "Tip £5",
  "tip1Url": "https://opencollective.com/ubuntubudgie/contribute/backer-40659/checkout",
  "tip2Label": "Tip £10",
  "tip2Url": "https://opencollective.com/ubuntubudgie/contribute/supporter-41583/checkout",
  "tip3Label": "Tip £20",
  "tip3Url": "https://opencollective.com/ubuntubudgie/contribute/bold-supporter-41582/checkout ",
  "tip4Label": "Tip £100",
  "tip4Url": "https://opencollective.com/ubuntubudgie/contribute/sponsor-40660/checkout",
  "usbDescription": "Have you ever wanted to get your custom USB with Ubuntu Budgie preloaded? Now you can - we have partnered with TheLinuxShop to bring you custom USB drives preloaded with Ubuntu Budgie releases. For each USB bought, the percentage of the price, goes back to Ubuntu Budgie for funding development and other costs.",
  "usbButtonText": "Buy Ubuntu Budgie USB",
  "usbButtonUrl": "https://affiliate.thelinuxshop.co.uk/ubuntubudgie",
  "installationTitle": "Installation instructions for x86 (click to expand)"
}
